### ISSUE TITLE
Switch to HTTPS

### ISSUE THREAD

**Issue by bycoffe** [ireapps/lightning-talks#22]
Given that the site requires a password (currently being sent in plain text), it would be great if it were switched to use HTTPS.

**Comment by aboutaaron** [comment]
:+1: Let me know if you need help on this front

**Comment by jeremyjbowers** [comment]
We'd definitely talk about HTTPS though I don't expect that this really rises to the level of concern given that the site could easily accept a throw-away password. This just isn't part of our threat model, honestly.

BUT if y'all have good ideas about how we might implement this at low-to-no cost without causing too much hassle for IRE (who kindly donate the server space and the devops), I'd love to talk.

I will go ahead and close this ticket, but either @bycoffe or @aboutaaron should get in touch with me about their thoughts.
