### ISSUE TITLE
Improve website security

### ISSUE THREAD

**Issue by xaranke** [ireapps/lightning-talks#24]
At the moment, the website has poor security that allows the creation of random user accounts and voting with these user accounts. As you are probably aware, someone could seriously tamper with the integrity of the voting by creating dummy accounts programmatically and using these accounts to vote. 

Some suggestions to remedy the situation:
- Switch over to HTTPS as mentioned in #22.
- Verify the email addresses being used are legitimate and not spam.
- Check `User-Agent`s to prevent bots from tampering with votes.

Hope this situation is rectified promptly. Thanks!

**Comment by jeremyjbowers** [comment]
Thank you for the input. These suggestions are welcome, and seem totally reasonable. However, the site is staffed entirely by volunteers, and this level of security is outside of our (limited) scope for work this year.

We do accept pull requests, and the entire site and architecture are open-source and in this repository. If you'd like to do the legwork for any of these, I'd gladly make the time to review and approve a pull request.

I'll close this ticket for now. If you have a PR for any of these items, make a new ticket and link it to the PR.
