### ISSUE TITLE
Post previous years lightning talk recordings

### ISSUE THREAD

**Issue by knowtheory** [ireapps/lightning-talks#25]
IRE has [catastrophically bad SEO game](http://lmgtfy.com/?q=NICAR+lightning+talks+2016).

Given that we've got [a site dedicated to lightning talks](http://lightningtalks.ire.org/), and also [a list of all of IRE/NICAR's videos](https://vimeo.com/irenicar/videos), i was thinking maybe we could just toss a page or so w/ embeds from the various talks that were given.

**Comment by knowtheory** [comment]
Whoops, accidentally hit submit before i was done.

But uh, i guess all the meet of the comment is there.

What do y'all think?

**Comment by jeremyjbowers** [comment]
Well, Sisi linked up the previous years from the home page, but maybe it could use some better SEO or something? Send me a pull request for updating this text: https://github.com/ireapps/lightning-talks/blob/master/templates/base.html#L99
